language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "mocks-server"
    token:
      secure: "$SONAR_TOKEN"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

script:
  - npm run lint
  - npm run test-ci
  - npm run coveralls
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'

deploy:
  provider: npm
  email: "javier.brea@gmail.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  skip_cleanup: true
